### ISSUE TITLE
Difficult to see search results

### ISSUE THREAD

**Issue by viccon** [JoosepAlviste/palenightfall.nvim#3]
Hi Joosep 👋 

I really like your theme and I have been using it for the past week or so. However, I struggle to see the search results:

<img width="1919" alt="Screenshot 2023-01-20 at 08 20 22" src="https://user-images.githubusercontent.com/12787673/213639383-d972edec-f6be-4e9d-ba3e-4bf591bf3ba7.png">

I forked your repository and changed `Search` and `IncSearch` to be:

```lua
Search       = { fg = c.background_darker, bg = c.yellow },
IncSearch    = { fg = c.background_darker, bg = c.yellow },
```

<img width="1918" alt="Screenshot 2023-01-20 at 08 21 13" src="https://user-images.githubusercontent.com/12787673/213639525-a71ef8ee-4237-424e-9d6e-60c2e23a6227.png">

Perhaps the low contrast search results are intentional. In that case you can just close this issue.

Have a nice day and thank you for creating this theme ⭐

**Comment by JoosepAlviste** [comment]
Hey, thanks for using the theme!

The lower contrast is mostly intentional since the usual high contrast search highlights in other themes are a bit too much to me. But I can definitely see how it can be hard to see the results (especially on a big screen with small-ish font size). Maybe it would be nice to add some optional higher contrast settings to this theme? There might be a few other cases where I have preferred to have lower contrast for highlights.

Until then, though, since this theme is quite extensible, you should be able to easily add overrides to the highlights like so:

```lua
local c = require('palenightfall').colors

require('palenightfall').setup({
  highlight_overrides = {
    Search    = { fg = c.background_darker, bg = c.yellow },
    IncSearch = { fg = c.background_darker, bg = c.yellow },
  },
})
```

So there should be no need to fork the repo just for customizing the theme

**Comment by viccon** [comment]
I think that sounds fair! The only issue I've had are the searches. Other than that I've just enjoyed the minimalism.

Thanks for the snippet - I'll add that to my config.
